 runtime: php55
 api_version: 1
 threadsafe: true

 handlers:
 - url: /
   static_files: www/testing.html
   upload: www/testing.html

 - url: /(.*)
   static_files: www/\1
   upload: www/(.*)